Add files via upload
kitedesigner/TestGuru pull request #13
Opened 2023-08-09 22:06 UTC by kitedesigner

2023-08-10 13:29 UTC, VidgarVii requested changes

2023-08-10 13:29 UTC, VidgarVii commented on config/README.md
> +* ...
нет списка сущностей

2023-08-10 13:29 UTC, VidgarVii commented on config/about.html
> +<!DOCTYPE html>
пересмотри скринкасты про публичные файлы. Этому файлу явно тут не место

2023-08-10 13:29 UTC, VidgarVii commented on config/application.rb
> +end
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-08-10 13:29 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :ru
чтобы не было ошибок в системе, надо еще добавить файл конфигураций в папку config/locales ru.yml. Содержание почти аналогичное как en.yml

2023-08-10 13:29 UTC, VidgarVii commented on config/author.html
> +  <a href="https://github.com/kitedesigner">GitHub</a>
ссылки на сторонние ресурсы правильно открывать в новой вкладке
тут https://github.com/kitedesigner/TestGuru/pull/13/files#diff-6646497e407acd0bd633f0ff16e3cc34f36338e1a2271381719a7de1493bb1cdR18 ссылка сделана на удивление правильно...

2023-08-10 13:29 UTC, VidgarVii commented on config/about.html
> +</html>
поправь отступы вложенных элементов

2023-08-11 06:39 UTC, VidgarVii requested changes

2023-08-11 06:39 UTC, VidgarVii commented on public/about/author/author.html
>  <body>
эта страница должна быть доступна по пути `/about/author/author`, а сейчас доступна по`/author`
ТЗ: "Добавьте статическую страницу /about/author с информацией об авторе (включая ссылку на GitHub профиль)"

2023-08-21 20:59 UTC, kitedesigner commented on config/README.md
> +* ...
добавила

2023-08-21 20:59 UTC, kitedesigner commented on config/about.html
> +<!DOCTYPE html>
перенесла

2023-08-21 20:59 UTC, kitedesigner commented on config/application.rb
> +end
добавила

2023-08-21 20:59 UTC, kitedesigner commented on config/application.rb
> +    config.i18n.default_locale = :ru
добавила

2023-08-21 20:59 UTC, kitedesigner commented on config/author.html
> +  <a href="https://github.com/kitedesigner">GitHub</a>
переделала ссылку

2023-11-12 22:07 UTC, closed without merging